version: "3.12.1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: "production"
      MONGODB_URL: <YOUR_MONGO_URL>
